/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Flexryhe (https://sketchfab.com/flexryhe)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/mechanical-keyboard-95d050e7a5954ff6ac7fbe4ac5301b3c
title: Mechanical Keyboard
*/

import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/mechanical_keyboard.glb");

  // Intervenimos el render loop
  useFrame((state) => {
    if (!group.current) return;
    if (!group.current) return;

    // PERILLA 1: Sensibilidad / Ganancia (Escala el rango del mouse)
    const factorX = 0.8;
    const factorY = 0.5; // Menos sensibilidad en Y para evitar revelar la base inferior

    // PERILLA 2: Límites estrictos en Radianes
    // Math.PI / 6 es 30 grados. El teclado rotará máximo 30° a los lados.
    const LIMITE_Y_ROTACION = Math.PI / 6; // Controla el paneo (Giro izquierda/derecha)
    const LIMITE_X_ROTACION = Math.PI / 12; // Controla el cabeceo (Inclinación arriba/abajo: 15°)

    // 1. Calculamos la intención pura del mouse con su ganancia
    let targetY = state.pointer.x * factorX;
    let targetX = -state.pointer.y * factorY; // Invertido para comportamiento natural

    // 2. ACOTA COERCITIVAMENTE (Clamp) los objetivos
    // Impide que el 'target' pase de los radianes permitidos
    targetY = THREE.MathUtils.clamp(
      targetY,
      -LIMITE_Y_ROTACION,
      LIMITE_Y_ROTACION,
    );
    targetX = THREE.MathUtils.clamp(
      targetX,
      -LIMITE_X_ROTACION,
      LIMITE_X_ROTACION,
    );

    // PERILLA 3: Factor de interpolación (0.05 = 5% de acercamiento por frame)
    const suavizado = 0.05;

    // 3. El modelo persigue al target acotado
    group.current.rotation.y = THREE.MathUtils.lerp(
      group.current.rotation.y,
      targetY,
      suavizado,
    );
    group.current.rotation.x = THREE.MathUtils.lerp(
      group.current.rotation.x,
      targetX,
      suavizado,
    );
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} position={[-0.45, 0, 0.23]}>
        <group
          rotation={[(3 * Math.PI) / 2, 4, (3 * Math.PI) / 5]}
          scale={0.01}
        >
          <group
            position={[-3.89, -1.05, -19.82]}
            rotation={[-1.58, 0, 1.52]}
            scale={[6.26, 6.26, 6.26]}
          >
            <mesh
              geometry={nodes.Board_Material001_0.geometry}
              material={materials["Material.001"]}
            />
          </group>
          <group
            position={[-3.89, 0.12, -19.74]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plate_Material004_0.geometry}
              material={materials["Material.004"]}
            />
          </group>
          <group
            position={[-7.47, 0.62, -42.47]}
            rotation={[-1.58, 0, 1.52]}
            scale={[1.08, 1.08, 1.25]}
          >
            <mesh
              geometry={nodes.Roller_Material009_0.geometry}
              material={materials["Material.009"]}
            />
            <mesh
              geometry={nodes.Roller_Material003_0.geometry}
              material={materials["Material.003"]}
            />
          </group>
          <group
            position={[-3.89, -0.27, -19.72]}
            rotation={[-1.58, 0, 1.52]}
            scale={5.86}
          >
            <mesh
              geometry={nodes.PCB_Material005_0.geometry}
              material={materials["Material.005"]}
            />
            <mesh
              geometry={nodes.PCB_copper_0.geometry}
              material={nodes.PCB_copper_0.material}
            />
          </group>
          <group
            position={[-9.13, 1.03, -15.13]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap_Dark_blue_0.geometry}
              material={nodes.Keycap_Dark_blue_0.material}
            />
          </group>
          <group
            position={[-4.82, 0.83, -14.88]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap001_Blue_0.geometry}
              material={nodes.Keycap001_Blue_0.material}
            />
          </group>
          <group
            position={[-8.93, 1, -18.82]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap002_White_0.geometry}
              material={nodes.Keycap002_White_0.material}
            />
          </group>
          <group
            position={[-8.93, 1, -18.82]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap003_White_0.geometry}
              material={nodes.Keycap003_White_0.material}
            />
          </group>
          <group
            position={[-8.93, 1, -18.82]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap004_White_0.geometry}
              material={nodes.Keycap004_White_0.material}
            />
          </group>
          <group
            position={[-8.93, 1, -18.82]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap005_White_0.geometry}
              material={nodes.Keycap005_White_0.material}
            />
          </group>
          <group
            position={[-8.49, 0.92, -26.69]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap006_Blue_0.geometry}
              material={nodes.Keycap006_Blue_0.material}
            />
          </group>
          <group
            position={[-8.49, 0.92, -26.69]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap007_Blue_0.geometry}
              material={nodes.Keycap007_Blue_0.material}
            />
          </group>
          <group
            position={[-8.49, 0.92, -26.69]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap008_Blue_0.geometry}
              material={nodes.Keycap008_Blue_0.material}
            />
          </group>
          <group
            position={[-8.49, 0.77, -26.69]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap009_Blue_0.geometry}
              material={nodes.Keycap009_Blue_0.material}
            />
          </group>
          <group
            position={[-8.06, 0.84, -34.56]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap010_White_0.geometry}
              material={nodes.Keycap010_White_0.material}
            />
          </group>
          <group
            position={[-8.06, 0.84, -34.56]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap011_White_0.geometry}
              material={nodes.Keycap011_White_0.material}
            />
          </group>
          <group
            position={[-8.06, 0.84, -34.56]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap012_White_0.geometry}
              material={nodes.Keycap012_White_0.material}
            />
          </group>
          <group
            position={[-8.06, 0.84, -34.56]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap013_White_0.geometry}
              material={nodes.Keycap013_White_0.material}
            />
          </group>
          <group
            position={[-4.82, 0.83, -14.88]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap014_Blue_0.geometry}
              material={nodes.Keycap014_Blue_0.material}
            />
          </group>
          <group
            position={[-6.69, 0.93, -14.99]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap015_White_0.geometry}
              material={nodes.Keycap015_White_0.material}
            />
          </group>
          <group
            position={[-6.69, 0.93, -14.99]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap016_White_0.geometry}
              material={nodes.Keycap016_White_0.material}
            />
          </group>
          <group
            position={[-6.69, 0.93, -14.99]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap017_White_0.geometry}
              material={nodes.Keycap017_White_0.material}
            />
          </group>
          <group
            position={[-6.69, 0.93, -14.99]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap018_White_0.geometry}
              material={nodes.Keycap018_White_0.material}
            />
          </group>
          <group
            position={[-6.69, 0.93, -14.99]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap019_White_0.geometry}
              material={nodes.Keycap019_White_0.material}
            />
          </group>
          <group
            position={[-6.69, 0.93, -14.99]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap020_White_0.geometry}
              material={nodes.Keycap020_White_0.material}
            />
          </group>
          <group
            position={[-6.69, 0.93, -14.99]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap021_White_0.geometry}
              material={nodes.Keycap021_White_0.material}
            />
          </group>
          <group
            position={[-6.69, 0.93, -14.99]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap022_White_0.geometry}
              material={nodes.Keycap022_White_0.material}
            />
          </group>
          <group
            position={[-6.69, 0.93, -14.99]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap023_White_0.geometry}
              material={nodes.Keycap023_White_0.material}
            />
          </group>
          <group
            position={[-6.69, 0.93, -14.99]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap024_White_0.geometry}
              material={nodes.Keycap024_White_0.material}
            />
          </group>
          <group
            position={[-6.69, 0.93, -14.99]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap025_White_0.geometry}
              material={nodes.Keycap025_White_0.material}
            />
          </group>
          <group
            position={[-6.69, 0.93, -14.99]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap026_White_0.geometry}
              material={nodes.Keycap026_White_0.material}
            />
          </group>
          <group
            position={[-6.69, 0.93, -14.99]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap027_White_0.geometry}
              material={nodes.Keycap027_White_0.material}
            />
          </group>
          <group
            position={[-6.69, 0.93, -14.99]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap028_Blue_0.geometry}
              material={nodes.Keycap028_Blue_0.material}
            />
          </group>
          <group
            position={[-6.69, 0.93, -14.99]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap029_Blue_0.geometry}
              material={nodes.Keycap029_Blue_0.material}
            />
          </group>
          <group
            position={[-2.95, 0.72, -14.78]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap030_Blue_0.geometry}
              material={nodes.Keycap030_Blue_0.material}
            />
          </group>
          <group
            position={[-1.09, 0.62, -14.68]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap031_Blue_0.geometry}
              material={nodes.Keycap031_Blue_0.material}
            />
          </group>
          <group
            position={[0.78, 0.54, -14.57]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap032_Dark_blue_0.geometry}
              material={nodes.Keycap032_Dark_blue_0.material}
            />
          </group>
          <group
            position={[0.78, 0.54, -14.57]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap033_Dark_blue_0.geometry}
              material={nodes.Keycap033_Dark_blue_0.material}
            />
          </group>
          <group
            position={[0.78, 0.54, -14.57]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap034_Dark_blue_0.geometry}
              material={nodes.Keycap034_Dark_blue_0.material}
            />
          </group>
          <group
            position={[-1.09, 0.62, -14.68]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap035_Dark_blue_0.geometry}
              material={nodes.Keycap035_Dark_blue_0.material}
            />
          </group>
          <group
            position={[-2.95, 0.72, -14.78]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap036_Blue_0.geometry}
              material={nodes.Keycap036_Blue_0.material}
            />
          </group>
          <group
            position={[-6.3, 1.1, 11.79]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap037_White_0.geometry}
              material={nodes.Keycap037_White_0.material}
            />
          </group>
          <group
            position={[-6.3, 1.1, 11.79]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap038_White_0.geometry}
              material={nodes.Keycap038_White_0.material}
            />
          </group>
          <group
            position={[-6.3, 1.1, 11.79]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap039_White_0.geometry}
              material={nodes.Keycap039_White_0.material}
            />
          </group>
          <group
            position={[-6.3, 1.1, 11.79]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap040_White_0.geometry}
              material={nodes.Keycap040_White_0.material}
            />
          </group>
          <group
            position={[-6.3, 1.1, 11.79]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap041_White_0.geometry}
              material={nodes.Keycap041_White_0.material}
            />
          </group>
          <group
            position={[-6.3, 1.1, 11.79]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap042_White_0.geometry}
              material={nodes.Keycap042_White_0.material}
            />
          </group>
          <group
            position={[-6.3, 1.1, 11.79]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap043_White_0.geometry}
              material={nodes.Keycap043_White_0.material}
            />
          </group>
          <group
            position={[-6.3, 1.1, 11.79]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap044_White_0.geometry}
              material={nodes.Keycap044_White_0.material}
            />
          </group>
          <group
            position={[-6.3, 1.1, 11.79]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap045_White_0.geometry}
              material={nodes.Keycap045_White_0.material}
            />
          </group>
          <group
            position={[-6.3, 1.1, 11.79]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap046_White_0.geometry}
              material={nodes.Keycap046_White_0.material}
            />
          </group>
          <group
            position={[-6.3, 1.1, 11.79]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap047_White_0.geometry}
              material={nodes.Keycap047_White_0.material}
            />
          </group>
          <group
            position={[-6.3, 1.1, 11.79]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap048_White_0.geometry}
              material={nodes.Keycap048_White_0.material}
            />
          </group>
          <group
            position={[-6.3, 1.1, 11.79]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap049_White_0.geometry}
              material={nodes.Keycap049_White_0.material}
            />
          </group>
          <group
            position={[-1.09, 0.62, -14.68]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap050_Blue_0.geometry}
              material={nodes.Keycap050_Blue_0.material}
            />
          </group>
          <group
            position={[-4.4, 0.98, 11.27]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap051_White_0.geometry}
              material={nodes.Keycap051_White_0.material}
            />
          </group>
          <group
            position={[-4.4, 0.98, 11.27]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap052_White_0.geometry}
              material={nodes.Keycap052_White_0.material}
            />
          </group>
          <group
            position={[-4.4, 0.98, 11.27]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap053_White_0.geometry}
              material={nodes.Keycap053_White_0.material}
            />
          </group>
          <group
            position={[-4.4, 0.98, 11.27]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap054_White_0.geometry}
              material={nodes.Keycap054_White_0.material}
            />
          </group>
          <group
            position={[-4.4, 0.98, 11.27]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap055_White_0.geometry}
              material={nodes.Keycap055_White_0.material}
            />
          </group>
          <group
            position={[-4.4, 0.98, 11.27]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap056_White_0.geometry}
              material={nodes.Keycap056_White_0.material}
            />
          </group>
          <group
            position={[-4.4, 0.98, 11.27]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap057_White_0.geometry}
              material={nodes.Keycap057_White_0.material}
            />
          </group>
          <group
            position={[-4.4, 0.98, 11.27]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap058_White_0.geometry}
              material={nodes.Keycap058_White_0.material}
            />
          </group>
          <group
            position={[-4.4, 0.98, 11.27]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap059_White_0.geometry}
              material={nodes.Keycap059_White_0.material}
            />
          </group>
          <group
            position={[-4.4, 0.98, 11.27]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap060_White_0.geometry}
              material={nodes.Keycap060_White_0.material}
            />
          </group>
          <group
            position={[-4.4, 0.98, 11.27]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap061_White_0.geometry}
              material={nodes.Keycap061_White_0.material}
            />
          </group>
          <group
            position={[-4.4, 0.98, 11.27]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap062_Dark_blue_0.geometry}
              material={nodes.Keycap062_Dark_blue_0.material}
            />
          </group>
          <group
            position={[0.78, 0.54, -14.57]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap063_Blue_0.geometry}
              material={nodes.Keycap063_Blue_0.material}
            />
          </group>
          <group
            position={[-2.39, 0.86, 8.9]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap064_White_0.geometry}
              material={nodes.Keycap064_White_0.material}
            />
          </group>
          <group
            position={[-2.39, 0.86, 8.9]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap065_White_0.geometry}
              material={nodes.Keycap065_White_0.material}
            />
          </group>
          <group
            position={[-2.39, 0.86, 8.9]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap066_White_0.geometry}
              material={nodes.Keycap066_White_0.material}
            />
          </group>
          <group
            position={[-2.39, 0.86, 8.9]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap067_White_0.geometry}
              material={nodes.Keycap067_White_0.material}
            />
          </group>
          <group
            position={[-2.39, 0.86, 8.9]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap068_White_0.geometry}
              material={nodes.Keycap068_White_0.material}
            />
          </group>
          <group
            position={[-2.39, 0.86, 8.9]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap069_White_0.geometry}
              material={nodes.Keycap069_White_0.material}
            />
          </group>
          <group
            position={[-2.39, 0.86, 8.9]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap070_White_0.geometry}
              material={nodes.Keycap070_White_0.material}
            />
          </group>
          <group
            position={[-2.39, 0.86, 8.9]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap071_White_0.geometry}
              material={nodes.Keycap071_White_0.material}
            />
          </group>
          <group
            position={[-2.39, 0.86, 8.9]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap072_White_0.geometry}
              material={nodes.Keycap072_White_0.material}
            />
          </group>
          <group
            position={[-2.39, 0.86, 8.9]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap073_White_0.geometry}
              material={nodes.Keycap073_White_0.material}
            />
          </group>
          <group
            position={[-2.39, 0.86, 8.9]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap074_Blue_0.geometry}
              material={nodes.Keycap074_Blue_0.material}
            />
          </group>
          <group
            position={[0.78, 0.54, -14.57]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap075_Blue_0.geometry}
              material={nodes.Keycap075_Blue_0.material}
            />
          </group>
          <group
            position={[0.78, 0.54, -14.57]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap076_Blue_0.geometry}
              material={nodes.Keycap076_Blue_0.material}
            />
          </group>
          <group
            position={[-0.2, 0.38, -30.76]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap077_Blue_0.geometry}
              material={nodes.Keycap077_Blue_0.material}
            />
          </group>
          <group
            position={[-0.2, 0.38, -30.76]}
            rotation={[-1.58, 0, -1.63]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Keycap079_Blue_0.geometry}
              material={nodes.Keycap079_Blue_0.material}
            />
          </group>
          <group
            position={[1.23, 0.46, -22.66]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane_Dark_blue_0.geometry}
              material={nodes.Plane_Dark_blue_0.material}
            />
          </group>
          <group
            position={[-9.19, 0.31, -15.12]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane001_Material007_0.geometry}
              material={nodes.Plane001_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane001_Material006_0.geometry}
              material={nodes.Plane001_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane001_copper_0.geometry}
              material={nodes.Plane001_copper_0.material}
            />
          </group>
          <group
            position={[-8.98, 0.27, -18.82]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane002_Material007_0.geometry}
              material={nodes.Plane002_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane002_Material006_0.geometry}
              material={nodes.Plane002_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane002_copper_0.geometry}
              material={nodes.Plane002_copper_0.material}
            />
          </group>
          <group
            position={[-8.55, 0.19, -26.69]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane003_Material007_0.geometry}
              material={nodes.Plane003_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane003_Material006_0.geometry}
              material={nodes.Plane003_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane003_copper_0.geometry}
              material={nodes.Plane003_copper_0.material}
            />
          </group>
          <group
            position={[-8.11, 0.11, -34.56]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane004_Material007_0.geometry}
              material={nodes.Plane004_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane004_Material006_0.geometry}
              material={nodes.Plane004_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane004_copper_0.geometry}
              material={nodes.Plane004_copper_0.material}
            />
          </group>
          <group
            position={[-6.73, 0.31, -14.98]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane007_Material007_0.geometry}
              material={nodes.Plane007_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane007_Material006_0.geometry}
              material={nodes.Plane007_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane007_copper_0.geometry}
              material={nodes.Plane007_copper_0.material}
            />
          </group>
          <group
            position={[-6.73, 0.31, -14.98]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane008_Material007_0.geometry}
              material={nodes.Plane008_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane008_Material006_0.geometry}
              material={nodes.Plane008_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane008_copper_0.geometry}
              material={nodes.Plane008_copper_0.material}
            />
          </group>
          <group
            position={[-5.29, 0.05, -40.8]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane010_Material007_0.geometry}
              material={nodes.Plane010_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane010_Material006_0.geometry}
              material={nodes.Plane010_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane010_copper_0.geometry}
              material={nodes.Plane010_copper_0.material}
            />
          </group>
          <group
            position={[-6.7, 0.3, -15.48]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane032_Material007_0.geometry}
              material={nodes.Plane032_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane032_Material006_0.geometry}
              material={nodes.Plane032_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane032_copper_0.geometry}
              material={nodes.Plane032_copper_0.material}
            />
          </group>
          <group
            position={[-6.57, 0.28, -17.81]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane033_Material007_0.geometry}
              material={nodes.Plane033_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane033_Material006_0.geometry}
              material={nodes.Plane033_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane033_copper_0.geometry}
              material={nodes.Plane033_copper_0.material}
            />
          </group>
          <group
            position={[-6.69, 0.3, -15.69]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane035_Material007_0.geometry}
              material={nodes.Plane035_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane035_Material006_0.geometry}
              material={nodes.Plane035_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane035_copper_0.geometry}
              material={nodes.Plane035_copper_0.material}
            />
          </group>
          <group
            position={[-6.66, 0.3, -16.11]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane036_Material007_0.geometry}
              material={nodes.Plane036_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane036_Material006_0.geometry}
              material={nodes.Plane036_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane036_copper_0.geometry}
              material={nodes.Plane036_copper_0.material}
            />
          </group>
          <group
            position={[-6.71, 0.3, -15.23]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane037_Material007_0.geometry}
              material={nodes.Plane037_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane037_Material006_0.geometry}
              material={nodes.Plane037_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane037_copper_0.geometry}
              material={nodes.Plane037_copper_0.material}
            />
          </group>
          <group
            position={[-6.54, 0.27, -18.28]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane038_Material007_0.geometry}
              material={nodes.Plane038_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane038_Material006_0.geometry}
              material={nodes.Plane038_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane038_copper_0.geometry}
              material={nodes.Plane038_copper_0.material}
            />
          </group>
          <group
            position={[-6.49, 0.26, -19.18]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane039_Material006_0.geometry}
              material={nodes.Plane039_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane039_Material007_0.geometry}
              material={nodes.Plane039_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane039_copper_0.geometry}
              material={nodes.Plane039_copper_0.material}
            />
          </group>
          <group
            position={[-6.71, 0.3, -15.23]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane040_Material007_0.geometry}
              material={nodes.Plane040_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane040_Material006_0.geometry}
              material={nodes.Plane040_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane040_copper_0.geometry}
              material={nodes.Plane040_copper_0.material}
            />
          </group>
          <group
            position={[-6.71, 0.3, -15.23]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane041_Material007_0.geometry}
              material={nodes.Plane041_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane041_Material006_0.geometry}
              material={nodes.Plane041_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane041_copper_0.geometry}
              material={nodes.Plane041_copper_0.material}
            />
          </group>
          <group
            position={[-6.34, 0.24, -21.99]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane042_Material006_0.geometry}
              material={nodes.Plane042_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane042_Material007_0.geometry}
              material={nodes.Plane042_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane042_copper_0.geometry}
              material={nodes.Plane042_copper_0.material}
            />
          </group>
          <group
            position={[-5.95, 0.17, -29]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane043_Material007_0.geometry}
              material={nodes.Plane043_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane043_Material006_0.geometry}
              material={nodes.Plane043_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane043_copper_0.geometry}
              material={nodes.Plane043_copper_0.material}
            />
          </group>
          <group
            position={[-5.43, 0.07, -38.32]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane048_Material007_0.geometry}
              material={nodes.Plane048_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane048_Material006_0.geometry}
              material={nodes.Plane048_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane048_copper_0.geometry}
              material={nodes.Plane048_copper_0.material}
            />
          </group>
          <group
            position={[-5.45, 0.08, -38.07]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.Plane051_Material007_0.geometry}
              material={nodes.Plane051_Material007_0.material}
            />
            <mesh
              geometry={nodes.Plane051_Material006_0.geometry}
              material={nodes.Plane051_Material006_0.material}
            />
            <mesh
              geometry={nodes.Plane051_copper_0.geometry}
              material={nodes.Plane051_copper_0.material}
            />
          </group>
          <group
            position={[-1.2, 0.19, -14.74]}
            rotation={[-1.58, 0, 1.52]}
            scale={[90, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube001_Stabiliser_plastic_0.geometry}
              material={nodes.Cube001_Stabiliser_plastic_0.material}
            />
            <mesh
              geometry={nodes.Cube001_Stabilisers_metall_0.geometry}
              material={nodes.Cube001_Stabilisers_metall_0.material}
            />
          </group>
          <group
            position={[-1.78, -0.05, -38.39]}
            rotation={[-1.58, 0, 1.52]}
            scale={[90, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube003_Stabiliser_plastic_0.geometry}
              material={nodes.Cube003_Stabiliser_plastic_0.material}
            />
            <mesh
              geometry={nodes.Cube003_Stabilisers_metall_0.geometry}
              material={nodes.Cube003_Stabilisers_metall_0.material}
            />
          </group>
          <group
            position={[-5.51, -0.05, -38.81]}
            rotation={[-1.58, 0, 1.52]}
            scale={[90, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube004_Stabiliser_plastic_0.geometry}
              material={nodes.Cube004_Stabiliser_plastic_0.material}
            />
            <mesh
              geometry={nodes.Cube004_Stabilisers_metall_0.geometry}
              material={nodes.Cube004_Stabilisers_metall_0.material}
            />
          </group>
          <group
            position={[1.35, 0.09, -23.78]}
            rotation={[-1.58, 0, -1.63]}
            scale={[90, 100, 100]}
          >
            <mesh
              geometry={nodes.Cube005_Stabiliser_plastic_0.geometry}
              material={nodes.Cube005_Stabiliser_plastic_0.material}
            />
            <mesh
              geometry={nodes.Cube005_Stabilisers_metall_0.geometry}
              material={nodes.Cube005_Stabilisers_metall_0.material}
            />
          </group>
          <group
            position={[-7.57, -0.38, -21.5]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 0.51]}
          >
            <mesh
              geometry={nodes["Screw_����������_0"].geometry}
              material={nodes["Screw_����������_0"].material}
            />
            <mesh
              geometry={nodes.Screw_Metal_0.geometry}
              material={nodes.Screw_Metal_0.material}
            />
          </group>
          <group
            position={[-8.22, -0.49, -33.36]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 0.51]}
          >
            <mesh
              geometry={nodes["Screw001_����������_0"].geometry}
              material={nodes["Screw001_����������_0"].material}
            />
            <mesh
              geometry={nodes.Screw001_Metal_0.geometry}
              material={nodes.Screw001_Metal_0.material}
            />
          </group>
          <group
            position={[-6.8, -0.51, -35.38]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 0.51]}
          >
            <mesh
              geometry={nodes["Screw002_����������_0"].geometry}
              material={nodes["Screw002_����������_0"].material}
            />
            <mesh
              geometry={nodes.Screw002_Metal_0.geometry}
              material={nodes.Screw002_Metal_0.material}
            />
          </group>
          <group
            position={[1.99, -0.54, -37.06]}
            rotation={[-1.58, 0, 1.52]}
            scale={[100, 100, 0.51]}
          >
            <mesh
              geometry={nodes["Screw003_����������_0"].geometry}
              material={nodes["Screw003_����������_0"].material}
            />
            <mesh
              geometry={nodes.Screw003_Metal_0.geometry}
              material={nodes.Screw003_Metal_0.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/mechanical_keyboard.glb");
