/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/isometric_gaming_room.glb 
Author: robbyrefta (https://sketchfab.com/robbyrefta)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/isometric-gaming-room-acb7828967a541348a645800ff1c2a9b
Title: Isometric Gaming Room
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Room(props) {
  const { nodes, materials } = useGLTF("/models/isometric_gaming_room.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Cube_0.geometry}
          material={materials.mat_lowpoly}
          position={[0, 0, 0.2]}
          scale={[1, 1, 0.201]}
        />
        <mesh
          geometry={nodes.Cube001_0.geometry}
          material={materials.mat_lowpoly}
          position={[0.103, -0.998, 0.109]}
          scale={[1, 0.111, 0.056]}
        />
        <mesh
          geometry={nodes.Cube002_0.geometry}
          material={materials.mat_lowpoly}
          position={[-0.833, -0.452, 1.107]}
          scale={[0.012, 0.012, 0.435]}
        />
        <mesh
          geometry={nodes.Cube003_0.geometry}
          material={materials.mat_lowpoly}
          position={[-0.833, -0.467, 1.107]}
          scale={[0.012, 0.012, 0.435]}
        />
        <mesh
          geometry={nodes.Cube004_0.geometry}
          material={materials.mat_lowpoly}
          position={[-0.785, -0.057, 1.525]}
          scale={1.048}
        />
        <mesh
          geometry={nodes.Cube011_0.geometry}
          material={materials.mat_lowpoly}
          position={[0.433, 0.56, 0.547]}
          scale={[1, 2.207, 0.955]}
        />
        <mesh
          geometry={nodes.Cube012_0.geometry}
          material={materials.mat_lowpoly}
          position={[0.916, 0.56, 0.292]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={[0.646, 1.85, 0.801]}
        />
        <mesh
          geometry={nodes.Cube013_0.geometry}
          material={materials.mat_lowpoly}
          position={[-0.029, 0.56, 0.292]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={[0.646, 1.85, 0.801]}
        />
        <mesh
          geometry={nodes.Cube014_0.geometry}
          material={materials.mat_lowpoly}
          position={[0.63, 0.56, 0.292]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={[0.646, 1.85, 0.801]}
        />
        <mesh
          geometry={nodes.Cube015_0.geometry}
          material={materials.mat_lowpoly}
          position={[0.692, 0.466, 0.487]}
          scale={[0.398, 1, 2.36]}
        />
        <mesh
          geometry={nodes.Cube016_0.geometry}
          material={materials.mat_lowpoly}
          position={[0.692, 0.466, 0.372]}
          scale={[0.398, 1, 2.36]}
        />
        <mesh
          geometry={nodes.Cube017_0.geometry}
          material={materials.mat_lowpoly}
          position={[0.765, 0.375, 0.485]}
        />
        <mesh
          geometry={nodes.Cube018_0.geometry}
          material={materials.mat_lowpoly}
          position={[0.765, 0.375, 0.368]}
        />
        <mesh
          geometry={nodes.Cube024_0.geometry}
          material={materials.mat_lowpoly}
          position={[0.326, -0.468, 0.567]}
          rotation={[0, 0, -1.133]}
          scale={1.471}
        />
        <mesh
          geometry={nodes.Cube025_0.geometry}
          material={materials.mat_lowpoly}
          position={[0.112, 0.528, 0.573]}
          rotation={[1.571, -0.542, -Math.PI / 2]}
          scale={[0.5, 0.64, 0.638]}
        />
        <mesh
          geometry={nodes.Cube029_0.geometry}
          material={materials.mat_lowpoly}
          position={[-0.695, 0.423, 0.129]}
          rotation={[0, 0, 0.483]}
          scale={[0.084, 0.073, 0.083]}
        />
        <mesh
          geometry={nodes.Cube032_0.geometry}
          material={materials.mat_lowpoly}
          position={[0.225, 0.747, 0.564]}
          rotation={[0, 0, 0.288]}
          scale={[0.072, 0.035, 0.008]}
        />
        <mesh
          geometry={nodes.Cube030_0.geometry}
          material={materials.mat_lowpoly}
          position={[0.609, 0.754, 0.564]}
          rotation={[0, 0, -0.242]}
          scale={[0.072, 0.035, 0.008]}
        />
        <mesh
          geometry={nodes.Cube031_0.geometry}
          material={materials.mat_lowpoly}
          position={[0.401, 0.528, 0.563]}
          scale={[0.14, 0.044, 0.006]}
        />
        <mesh
          geometry={nodes.Cube033_0.geometry}
          material={materials.mat_lowpoly}
          position={[0.627, 0.528, 0.563]}
          rotation={[0, 0, 0.359]}
          scale={[0.016, 0.028, 0.004]}
        />
        <mesh
          geometry={nodes.Icosphere_0.geometry}
          material={materials.mat_lowpoly}
          position={[-0.722, 0.478, 0.259]}
          scale={0.038}
        />
        <mesh
          geometry={nodes.Icosphere001_0.geometry}
          material={materials.mat_lowpoly}
          position={[-0.748, 0.48, 0.25]}
          scale={0.027}
        />
        <mesh
          geometry={nodes.Icosphere002_0.geometry}
          material={materials.mat_lowpoly}
          position={[-0.751, 0.495, 0.286]}
          scale={0.027}
        />
        <mesh
          geometry={nodes.Icosphere003_0.geometry}
          material={materials.mat_lowpoly}
          position={[-0.637, 0.349, 0.151]}
          scale={0.027}
        />
        <mesh
          geometry={nodes.Icosphere004_0.geometry}
          material={materials.mat_lowpoly}
          position={[-0.538, 0.391, 0.161]}
          scale={0.027}
        />
        <mesh
          geometry={nodes.Cube027_0.geometry}
          material={materials.mat_lowpoly}
          position={[-0.734, 0.751, 0.604]}
          scale={0.008}
        />
        <mesh
          geometry={nodes.Icosphere005_0.geometry}
          material={materials.mat_lowpoly}
          position={[-0.703, 0.504, 0.259]}
          scale={0.03}
        />
        <mesh
          geometry={nodes.Cube005_0.geometry}
          material={materials.mat_lowpoly}
          position={[-0.866, 0.56, 0.292]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={[0.646, 1.85, 0.801]}
        />
        <mesh
          geometry={nodes.Cylinder_0.geometry}
          material={materials.mat_lowpoly}
          position={[-0.961, -0.066, 0.13]}
          scale={[0.474, 0.474, 0.005]}
        />
        <mesh
          geometry={nodes.Cube006_0.geometry}
          material={materials.mat_lowpoly}
          position={[-0.354, 0.78, 0.166]}
          scale={[0.398, 1, 2.36]}
        />
        <mesh
          geometry={nodes.Plane_0.geometry}
          material={materials.mat_lowpoly}
          position={[1.388, 2.764, 0.562]}
        />
        <mesh
          geometry={nodes.Plane001_0.geometry}
          material={materials.material}
          position={[0.366, 2.817, 0.649]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/isometric_gaming_room.glb");
