/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/gaming_laptop.glb --transform 
Files: public/models/gaming_laptop.glb [15.81MB] > /home/samuel-nelo/projects/samuel-nelo-portfolio-v2/gaming_laptop-transformed.glb [865.13KB] (95%)
Author: Blue Lantern (https://sketchfab.com/genoris2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-laptop-4e72a2078b3c4a75a821ab09830693fe
Title: Gaming Laptop
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/gaming_laptop.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
        position={[-1.199, 0.096, 0]}
        rotation={[0, 0, -1.38]}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials["Material.004"]}
        position={[-1.199, 0.096, 0]}
        rotation={[0, 0, -1.38]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.PaletteMaterial002}
        position={[-1.199, 0.096, 0]}
        rotation={[0, 0, -1.38]}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials["Material.009"]}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials["Material.010"]}
      />
    </group>
  );
}

useGLTF.preload("/models/gaming_laptop.glb");
