/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/react_logo_circle.glb --transform 
Files: public/models/react_logo_circle.glb [1.48MB] > /home/samuel-nelo/projects/samuel-nelo-portfolio-v2/react_logo_circle-transformed.glb [64.32KB] (96%)
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-circle-540ff21ac0f54a038df6f634c7cce726
Title: React logo circle
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/react_logo_circle.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["React-Logo_Material002_0"].geometry}
        material={materials["Material.002"]}
        position={[0, 0.079, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.392, 0.392, 0.527]}
      />
      <mesh
        geometry={nodes.Backdrop_Material001_0.geometry}
        material={materials["Material.001"]}
        position={[0, 0.079, -0.171]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[2.479, 2.479, 0.527]}
      />
    </group>
  );
}

useGLTF.preload("/models/react_logo_circle.glb");
